services:
  dash_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"      # Expose le port 8050 de l'application Dash
    volumes:
      - .:/app           # Monte le dossier local pour voir les changements en temps réel
    command: python app.py  # Démarre l'application